##
## Workspace - examples of using an external prebuilt llvm
##

workspace(name = "bazel_llvm_bridge_examples")

local_repository(
    name = "bazel_llvm_bridge",
    path = "..",
)

load("@bazel_llvm_bridge//llvm:llvm_configure.bzl", "llvm_configure")

llvm_configure(
    name = "local_llvm",
    # The LLVM_INSTALL_PREFIX environment variable must point to
    # a local llvm/clang installation.
    # The Z3_INSTALL_PREFIX environment variable must point to
    # a local Z3 Solver installation when LLVM is linked against Z3.
)
