##
## Workspace - examples of using an external prebuilt llvm
##

workspace(name = "bazel_llvm_bridge_examples")

local_repository(
    name = "bazel_llvm_bridge",
    path = "..",
)

load("@bazel_llvm_bridge//llvm:llvm_configure.bzl", "llvm_configure")

llvm_configure(
    name = "local_llvm",
    llvm_prefix = "",            # default value: llvm_
    clang_prefix = "cl_",        # default value: clang_
    libcxx_prefix = "cxx_",      # default value: libcxx_
    mlir_prefix = "ml_",         # default value: mlir_
    add_headers_to_deps = False, # default value: True

    # Either the LLVM_INSTALL_PREFIX environment variable must point to
    # a local llvm/clang installation or the 'urls', 'sha256' and, optionaly,
    # 'strip_prefix' must be specified.

    # If a build_file (and optionaly config_file) are specified,
    # the repository rule will generate no BUILD file, the specified one will
    # be taken into account instead.
)
